### PR TITLE
Display error message for invalid Log Commands

### LINKED ISSUE #172: [PE-D] No feedback from the command box for an incorrect log command
#### Issue description

There is no feedback on what is wrong with my log command if I input it as such.
"log starbucks utown hr/10"

#### Steps to reproduce the issue

1.  Type "log starbucks utown hr/10" into the command box.
2.  Hit enter
3.  Nothing happens

#### What's the expected result?

-  Successful command execution or error explaining the problem with command

#### What's the actual result?

- No feedback provided

#### Additional details / screenshot

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: KelvinSoo/ped#3

### PR DESCRIPTION
**Pull request by ruoyann**
Feels a little brute-forcey not sure if there's a better way to do this 

Resolves #172 #208 

Should we state in the UG that `log -ra` will ignore anything that comes after it? so `log -ra n/starbucks hr/2` will just reset every study spot's hours as usual, and wont throw error message? (This is for #186 )

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 1]
```diff
@@ -29,6 +30,23 @@ public LogCommand parse(String args) throws ParseException {
...
+        if ((!arePrefixesPresent(argMultimap, PREFIX_NAME)
+                || !argMultimap.getPreamble().isEmpty()) && !args.contains("-r")) {
+            System.out.println("Entering error1");
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, LogCommand.MESSAGE_USAGE));
+        }
+
+        // log -r hi (supposed to be log -r n/hi)
+        // won't throw error for log -r
+        System.out.println(args);
+        System.out.println(args.equals("-r"));
```
Comment (joenzkimchan) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:43]: Print statements!

Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java]: thanks!

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 2]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
...
+                        || flag.equals(LogCommand.FLAG_RESET_ALL));
 
                 // Reset only depends on if a name is given,
                 // It should ignore any hour provided, and should not throw an error even if hour is null.
                 if (flag.equals("r")) {
-                    return new LogCommand(studySpot, null, isNamePresent,
-                            false, !isNamePresent);
+                    return new LogCommand(studySpot, null, isNamePresent, false, !isNamePresent);
+                }
+                else if (flag.equals("ra")) {
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:59]: `else if` should be on the same line as the curly brace in line 58

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 3]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
                             LogCommand.MESSAGE_ONE_FLAG));
                 }
                 String flag = argMultimap.getValue(PREFIX_FLAG).get();
-                assert(flag.equals(LogCommand.FLAG_RESET) || flag.equals(LogCommand.FLAG_OVERRIDE));
+                assert(flag.equals(LogCommand.FLAG_RESET) || flag.equals(LogCommand.FLAG_OVERRIDE)
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:51]: Could you include a Parse exception and error msg for unsupported flags? currently no error msg for 
`log n/central library -s`

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 4]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
...
                 // Reset only depends on if a name is given,
                 // It should ignore any hour provided, and should not throw an error even if hour is null.
                 if (flag.equals("r")) {
-                    return new LogCommand(studySpot, null, isNamePresent,
-                            false, !isNamePresent);
+                    return new LogCommand(studySpot, null, isNamePresent, false, !isNamePresent);
+                }
+                else if (flag.equals("ra")) {
+                    return new LogCommand(studySpot, null, false, false, true);
                 } else {
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:61]: Perhaps we should explicitly check for `isOverride && isNamePresent` in an `else if` case and use `else` for throwing exceptions.
This can help to improve the overall code quality as well.
Refer to [Using default branch](https://nus-cs2103-ay2122s1.github.io/website/se-book-adapted/chapters/codeQuality.html#use-the-default-branch)

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 5]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
                             LogCommand.MESSAGE_ONE_FLAG));
                 }
                 String flag = argMultimap.getValue(PREFIX_FLAG).get();
-                assert(flag.equals(LogCommand.FLAG_RESET) || flag.equals(LogCommand.FLAG_OVERRIDE));
+                assert(flag.equals(LogCommand.FLAG_RESET) || flag.equals(LogCommand.FLAG_OVERRIDE)
+                        || flag.equals(LogCommand.FLAG_RESET_ALL));
 
                 // Reset only depends on if a name is given,
                 // It should ignore any hour provided, and should not throw an error even if hour is null.
                 if (flag.equals("r")) {
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:56]:
```suggestion
                if (flag.equals("r") && isNamePresent) {
```

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 6]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
...
-                    return new LogCommand(studySpot, null, isNamePresent,
-                            false, !isNamePresent);
+                    return new LogCommand(studySpot, null, isNamePresent, false, !isNamePresent);
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:57]:
```suggestion
                    return new LogCommand(studySpot, null, true, false, false);
```
I think this would be easier to read if it only caters for one case.

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 7]
```diff
@@ -25,7 +26,14 @@
     public LogCommand parse(String args) throws ParseException {
         ArgumentMultimap argMultimap =
                 ArgumentTokenizer.tokenize(args, PREFIX_FLAG, PREFIX_NAME, PREFIX_HOURS);
-        Name studySpot = null;
+
+        // If command has no n/ and it's not a reset all command
+        if ((!arePrefixesPresent(argMultimap, PREFIX_NAME)
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:31]: Refer to my comment as line 60. This would be the default case and an exception is thrown. `arePrefixesPresent` would not be needed as you can make use of `isNamePresent` since we are only checking for name

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java [hunk 8]
```diff
@@ -40,23 +48,32 @@ public LogCommand parse(String args) throws ParseException {
...
         } catch (NoSuchElementException e) {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, LogCommand.MESSAGE_USAGE));
         }
+    }
 
+    /**
+     * Returns true if none of the prefixes contains empty {@code Optional} values in the given
+     * {@code ArgumentMultimap}.
+     */
+    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
```
Comment (mslevis) [inline src/main/java/seedu/address/logic/parser/LogCommandParser.java:76]: Perhaps we can use `argMultimap.getValue(PREFIX_NAME).isPresent()` to retrieve name instead of creating a method as this method is only used once. Nevertheless, this could be written as a generic method in ParserUtil if many Parsers make use of this logic so that we avoid duplicate code across the different parsers.

**Review by mslevis — CHANGES_REQUESTED** [review]
I left some suggestions to improve on code quality as well as including an error message for unsupported flags.

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java (hunk 2 above)
Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java:59]: ok thank u!

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java (hunk 3 above)
Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java:51]: ok done!

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java (hunk 5 above)
Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java:56]: ok thank u!

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java (hunk 6 above)
Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java:57]: okay thank u

File: src/main/java/seedu/address/logic/parser/LogCommandParser.java (hunk 8 above)
Comment (ruoyann) [reply src/main/java/seedu/address/logic/parser/LogCommandParser.java:76]: I have abstracted it out!

**Review by mslevis — APPROVED** [review]
